#include "svg_diagram.h"

#include <gtest/gtest.h>

#include "../test_utils.h"
using namespace std;
using namespace svg_diagram;

TEST(TestSVGDrawComment, DefaultComment) {
    SVGDiagram diagram;
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
    const auto svg = diagram.render();
    const auto expected = R"s(<svg width="8" height="8" viewBox="0 0 8 8" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(4,4) scale(1.0)"/>
</svg>
)s";
    compareSVGContent(svg, expected);
}

TEST(TestSVGDrawComment, EscapeComment) {
    SVGDiagram diagram;
    diagram.clearSVGDraw();
    diagram.setBackgroundColor("white");
    diagram.addSVGDraw(make_unique<SVGDrawComment>("A <!-- B --> C"));
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
    const auto svg = diagram.render();
    const auto expected = R"s(<svg width="8" height="8" viewBox="0 0 8 8" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(4,4) scale(1.0)">
    <rect x="-4" y="-4" width="8" height="8" fill="white"/>
    <!-- A <!‑‑ B ‑‑> C -->
  </g>
</svg>
)s";
    compareSVGContent(svg, expected);
}
