#include "svg_diagram.h"

#include <format>
#include <gtest/gtest.h>

#include "../test_utils.h"
using namespace std;
using namespace svg_diagram;

#ifndef SVG_DIAGRAM_ENABLE_PANGO_CAIRO
TEST(TestSVGDrawText, OneLineTextAutoSize) {
    SVGDiagram diagram;
    diagram.clearSVGDraw();
    diagram.setBackgroundColor("white");
    auto text = make_unique<SVGDrawText>(0.0, 0.0, "Hello world!");
    auto svg = text->generateXMLElements()[0]->toString();
    EXPECT_EQ(svg, R"(<text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">Hello world!</text>)" + string("\n"));
    diagram.addSVGDraw(std::move(text));
    svg = diagram.render();
    const auto expected = R"s(<svg width="92" height="22" viewBox="0 0 92 22" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(46,11) scale(1.0)">
    <rect x="-46" y="-11" width="92" height="22" fill="white"/>
    <text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">Hello world!</text>
  </g>
</svg>
)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDrawText, TwoLinesAutoSize) {
    SVGDiagram diagram;
    diagram.clearSVGDraw();
    diagram.setBackgroundColor("white");
    auto text = make_unique<SVGDrawText>(0.0, 0.0, "Hello world!\n世界你好！");
    auto svg = text->generateXMLElements()[0]->toString();
    auto expected = R"(<text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">
  <tspan x="0" dy="-0.6em">Hello world!</tspan>
  <tspan x="0" dy="1.2em">世界你好！</tspan>
</text>
)";
    compareSVGContent(svg, expected);
    diagram.addSVGDraw(std::move(text));
    svg = diagram.render();
    expected = R"s(<svg width="113" height="38.8" viewBox="0 0 113 38.8" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(56.5,19.4) scale(1.0)">
    <rect x="-56.5" y="-19.4" width="113" height="38.8" fill="white"/>
    <text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">
      <tspan x="0" dy="-0.6em">Hello world!</tspan>
      <tspan x="0" dy="1.2em">世界你好！</tspan>
    </text>
  </g>
</svg>
)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDrawText, ThreeLinesAutoSize) {
    SVGDiagram diagram;
    diagram.clearSVGDraw();
    diagram.setBackgroundColor("white");
    auto text = make_unique<SVGDrawText>(0.0, 0.0, "Hello world!\n世界你好！\r\nSalve, mundus!");
    auto svg = text->generateXMLElements()[0]->toString();
    auto expected = R"(<text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">
  <tspan x="0" dy="-1.2em">Hello world!</tspan>
  <tspan x="0" dy="1.2em">世界你好！</tspan>
  <tspan x="0" dy="1.2em">Salve, mundus!</tspan>
</text>
)";
    compareSVGContent(svg, expected);
    diagram.addSVGDraw(std::move(text));
    svg = diagram.render();
  expected = R"s(<svg width="113" height="55.6" viewBox="0 0 113 55.6" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(56.5,27.8) scale(1.0)">
    <rect x="-56.5" y="-27.8" width="113" height="55.6" fill="white"/>
    <text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">
      <tspan x="0" dy="-1.2em">Hello world!</tspan>
      <tspan x="0" dy="1.2em">世界你好！</tspan>
      <tspan x="0" dy="1.2em">Salve, mundus!</tspan>
    </text>
  </g>
</svg>
)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}
#endif
