#include "svg_diagram.h"

#include <gtest/gtest.h>

#include "../test_utils.h"
using namespace std;
using namespace svg_diagram;

TEST(TestSVGDrawLine, SingleLineAutoSize) {
    SVGDiagram diagram;
    diagram.clearSVGDraw();
    diagram.setBackgroundColor("white");
    auto line = make_unique<SVGDrawLine>(0.0, 0.0, 20.0, 30.0);
    line->setAttribute(SVG_ATTR_KEY_STROKE, "red");
    auto svg = line->generateXMLElements()[0]->toString();
    compareSVGContent(svg, R"(<line x1="0" y1="0" x2="20" y2="30" stroke="red"/>)" + string("\n"));
    diagram.addSVGDraw(std::move(line));
    svg = diagram.render();
    const auto expected = R"s(<svg width="28" height="38" viewBox="0 0 28 38" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(4,4) scale(1.0)">
    <rect x="-4" y="-4" width="28" height="38" fill="white"/>
    <line x1="0" y1="0" x2="20" y2="30" stroke="red"/>
  </g>
</svg>
)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDrawLine, TwoLinesAutoSize) {
    SVGDiagram diagram;
    diagram.clearSVGDraw();
    diagram.setBackgroundColor("white");
    auto line1 = make_unique<SVGDrawLine>(0.0, 0.0, 20.0, 30.0);
    line1->setAttribute(SVG_ATTR_KEY_STROKE, "red");
    auto svg = line1->generateXMLElements()[0]->toString();
    compareSVGContent(svg, R"(<line x1="0" y1="0" x2="20" y2="30" stroke="red"/>)" + string("\n"));
    diagram.addSVGDraw(std::move(line1));
    auto line2 = make_unique<SVGDrawLine>(10.0, 20.0, 5.0, 40.0);
    line2->setAttribute(SVG_ATTR_KEY_STROKE, "blue");
    svg = line2->generateXMLElements()[0]->toString();
    compareSVGContent(svg, R"(<line x1="10" y1="20" x2="5" y2="40" stroke="blue"/>)" + string("\n"));
    diagram.addSVGDraw(std::move(line2));
    svg = diagram.render();
    const auto expected = R"s(<svg width="28" height="48" viewBox="0 0 28 48" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(4,4) scale(1.0)">
    <rect x="-4" y="-4" width="28" height="48" fill="white"/>
    <line x1="0" y1="0" x2="20" y2="30" stroke="red"/>
    <line x1="10" y1="20" x2="5" y2="40" stroke="blue"/>
  </g>
</svg>
)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}
