#include "svg_diagram.h"
#include "test_utils.h"

#include <vector>
#include <format>
#include <gtest/gtest.h>
using namespace std;
using namespace svg_diagram;

TEST(TestSVGDiagram, AddSVGDraws) {
    SVGDiagram diagram;
    diagram.enableDebug();
    auto comments = vector<unique_ptr<SVGDraw>>();
    comments.emplace_back(make_unique<SVGDrawComment>("foo1"));
    comments.emplace_back(make_unique<SVGDrawComment>("bar1"));
    auto group = make_unique<SVGDrawGroup>(comments);
    comments.clear();
    comments.emplace_back(make_unique<SVGDrawComment>("foo2"));
    comments.emplace_back(make_unique<SVGDrawText>());
    diagram.addSVGDraw(std::move(group));
    diagram.addSVGDraw(comments);
    const auto svg = diagram.render();
    const auto expected = R"(<g>
  <!-- foo1 -->
  <!-- bar1 -->
</g>
<!-- foo2 -->
<text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14"/>)";
    compareSVGWithDefaultGraphContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDiagram, DuplicateNodeId) {
    SVGDiagram diagram;
    auto node = diagram.addNode("foo");
    EXPECT_THROW(diagram.addNode("foo"), runtime_error);
    EXPECT_THROW(diagram.addNode("foo", node), runtime_error);
}

TEST(TestSVGDiagram, DuplicateEdgeId) {
    SVGDiagram diagram;
    auto edge = diagram.addEdge("foo");
    EXPECT_THROW(diagram.addEdge("foo"), runtime_error);
    EXPECT_THROW(diagram.addEdge("foo", edge), runtime_error);
}

TEST(TestSVGDiagram, DuplicateSubgraphId) {
    SVGDiagram diagram;
    auto subgraph = diagram.addSubgraph("foo");
    EXPECT_THROW(diagram.addSubgraph("foo"), runtime_error);
    EXPECT_THROW(diagram.addSubgraph("foo", subgraph), runtime_error);
    EXPECT_NO_THROW(diagram.addSubgraph("bar", subgraph));
}

TEST(TestSVGDiagram, FixedViewBox) {
    SVGDiagram diagram;
    diagram.setFixedViewBox(-10, -10, 50, 50);
    const auto node = diagram.addNode("A");
    node->setFixedSize(40, 40);
    node->setFillColor("green");
    const auto svg = diagram.render();
    const auto expected = R"s(<svg width="50" height="50" viewBox="-10 -10 50 50" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="scale(1.0)">
    <!-- Node: A -->
    <g class="node" id="A">
      <title>A</title>
      <ellipse cx="0" cy="0" rx="20" ry="20" fill="green" stroke="black"/>
    </g>
  </g>
</svg>)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDiagram, FixedViewBoxRotation) {
    SVGDiagram diagram;
    diagram.setBackgroundColor("white");
    diagram.setFixedViewBox(-10, -10, 50, 50);
    diagram.setRotation(90);
    const auto node = diagram.addNode("A");
    node->setFixedSize(40, 40);
    node->setFillColor("green");
    node->setLabel("A");
    const auto svg = diagram.render();
    const auto expected = R"s(<svg width="50" height="50" viewBox="-10 -10 50 50" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="scale(1.0) rotate(90,15,15)">
    <rect x="-25" y="-25" width="50" height="50" fill="white"/>
    <!-- Node: A -->
    <g class="node" id="A">
      <title>A</title>
      <ellipse cx="0" cy="0" rx="20" ry="20" fill="green" stroke="black"/>
      <text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">A</text>
    </g>
  </g>
</svg>)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDiagram, FixedViewBoxRotationCenter) {
    SVGDiagram diagram;
    diagram.setBackgroundColor("white");
    diagram.setFixedViewBox(-10, -10, 50, 50);
    diagram.setRotation(90, 20, 20);
    const auto node = diagram.addNode("A");
    node->setFixedSize(40, 40);
    node->setFillColor("green");
    node->setLabel("A");
    const auto svg = diagram.render();
    const auto expected = R"s(<svg width="50" height="50" viewBox="-10 -10 50 50" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="scale(1.0) rotate(90,20,20)">
    <rect x="-25" y="-25" width="50" height="50" fill="white"/>
    <!-- Node: A -->
    <g class="node" id="A">
      <title>A</title>
      <ellipse cx="0" cy="0" rx="20" ry="20" fill="green" stroke="black"/>
      <text x="0" y="0" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">A</text>
    </g>
  </g>
</svg>)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}

TEST(TestSVGDiagram, Rotation) {
    SVGDiagram diagram;
    diagram.setBackgroundColor("white");
    diagram.setRotation(90);
    const auto node = diagram.addNode("A");
    node->setCenter(1000, -1000);
    node->setFixedSize(40, 40);
    node->setFillColor("green");
    node->setLabel("A");
    const auto svg = diagram.render();
    const auto expected = R"s(<svg width="56" height="56" viewBox="0 0 56 56" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Generated by: https://github.com/CyberZHG/SVGDiagram -->
  <g id="graph0" class="graph" transform="translate(-972,1028) scale(1.0) rotate(90,1000,-1000)">
    <rect x="972" y="-1028" width="56" height="56" fill="white"/>
    <!-- Node: A -->
    <g class="node" id="A">
      <title>A</title>
      <ellipse cx="1000" cy="-1000" rx="20" ry="20" fill="green" stroke="black"/>
      <text x="1000" y="-1000" text-anchor="middle" dominant-baseline="central" font-family="Times,serif" font-size="14">A</text>
    </g>
  </g>
</svg>)s";
    compareSVGContent(svg, expected);
    const ::testing::TestInfo* info = ::testing::UnitTest::GetInstance()->current_test_info();
    diagram.render(format("{}_{}.svg", info->test_suite_name(), info->name()));
}
